# 12.promise

## **一、Promise的作用**

在ajax请求数据的过程中，我们可以异步拿到我们想要的数据，然后在回调中做相应的数据处理。这样做看上去并没有什么麻烦，但是这个时候，我们还需要做另外一个ajax请求，这个新的ajax请求的其中一个参数，得从上一个ajax请求中获取，这个时候我们就需要在回调函数中再写一个异步请求，然后在这个异步函数的回调函数里在写相应的数据处理。要是连续嵌套个三四层，往往就很恶心了。写起来就像下面这样：

```javascript
$.ajax({
    type:'get',
    url:'url_1', 
    data: 'data'
    success : function(res){
        //相应的数据处理
        var data = res.data
        $.ajax({
            type:'get',
            url:'url_2', 
            data: data
            success : function(res){
                //相应的数据处理
                $.ajax({
                    type:'get',
                    url:'url_3', 
                    data: data
                    success : function(res){
                        //相应的数据处理
                    }
                })
            }
        })
    }
})
```

 在这种情况下Promise就能发挥它的威力了；具体用法如下

```javascript
// 传统写法
step1(function (value1) {
  step2(value1, function(value2) {
    step3(value2, function(value3) {
      step4(value3, function(value4) {
        // ...
      });
    });
  });
});

// Promise 的写法
(new Promise(step1))
  .then(step2)
  .then(step3)
  .then(step4);
```

## **三、什么是Promise对象：**

 Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。它由社区最早提出和实现，ES6 将其写进了语言标准，统一了用法，原生提供了`Promise`对象。

`Promise` 对象有三种状态，他们分别是：

* pending: 等待中，或者进行中，表示还没有得到结果
* resolved\(Fulfilled\): 已经完成，表示得到了我们想要的结果，可以继续往下执行
* rejected: 也表示得到结果，但是由于结果并非我们所愿，因此拒绝执行

这三种状态不受外界影响，而且状态只能从 `pending` 改变为 `resolved` 或者`rejected` ，并且不可逆。在 `Promise` 对象的构造函数中，`resolve` 和 `reject` 就是用来处理Promise的状态变化。一般来说，调用 `resolve` 或 `reject` 以后，Promise 的使命就完成了，后继操作应该放到 `then` 或者 `catch` 方法里面，而不应该直接写在 `resolve()` 或 `reject()`的后面 **\(事实的情况是，`resolve()` 或 `reject()` 的后面的代码也不会执行\)**。

### **promise基本用法**

ES6 规定，`Promise`对象是一个构造函数，用来生成`Promise`实例。下面代码创造了一个`Promise`实例。

```javascript
const promise = new Promise(function(resolve, reject) {
  // ... some code

  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
```

`Promise`构造函数接受**一个函数**作为参数，该**函数的两个参数**分别是`resolve`和`reject`。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。

**`resolve`函数的作用**是，将`Promise`对象的状态从“未完成”变为“成功”（即从 pending 变为 resolved），在异步操作成功时调用，并将异步操作的**结果**，作为参数传递出去；

**`reject`函数的作用**是，将`Promise`对象的状态从“未完成”变为“失败”（即从 pending 变为 rejected），在异步操作失败时调用，并将异步操作报出的**错误**，作为参数传递出去。

`Promise`实例生成以后，可以用**`then`方法**分别指定`resolved`状态和`rejected`状态的回调函数。

**注意：new Promise\(\) 里的函数是立刻执行的**

需要注意的的是，`new Promise()` 里的函数是立刻执行的 ，也就是说 ，当你执行下面这段代码时，就已经开始执行异步请求了：

```javascript
<script>
new Promise(function(resolve,reject){
    $.ajax({
        type:'post',
        dataType: 'jsonp',
        url:'http://api.money.126.net/data/feed/0000001,1399001',
        data:{
        },
        success : function(res){
            console.log(res) ;
            resolve(res) ;
        },
        error:function(res){
            reject(res) ;
        }
    })
});
```

### then方法：

`then`方法可以接受两个回调函数作为参数。第一个回调函数是`Promise`对象的状态变为`resolved`时调用，第二个回调函数是`Promise`对象的状态变为`rejected`时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都**接受`Promise`对象传出的值作为参数**（接收resolve处理结果或者reject的错误结果）**。**

```javascript
promise.then(function(value) {
  // success
}, function(error) {
  // failure
});
```

**value为resolve函数返回值，error为reject函数的返回值，注意：then\(\) 函数的返回值一定是 Promise 对象，由此，then函数可以链式调用。**

{% code title="then方法实例" %}
```javascript
getJSON("/post/1.json").then(function(post) {
  return getJSON(post.commentURL);
}).then(function funcA(comments) {
  console.log("resolved: ", comments);
}, function funcB(err){
  console.log("rejected: ", err);
});
```
{% endcode %}

 上面代码中，第一个`then`方法指定的回调函数，返回的是另一个`Promise`对象。这时，第二个`then`方法指定的回调函数，就会等待这个新的`Promise`对象状态发生变化。如果变为`resolved`，就调用`funcA`，如果状态变为`rejected`，就调用`funcB`。

如果采用箭头函数，上面的代码可以写得更简洁。

```javascript
getJSON("/post/1.json").then(
  post => getJSON(post.commentURL)
).then(
  comments => console.log("resolved: ", comments),
  err => console.log("rejected: ", err)
);
```

### Promise.prototype.catch\(\) <a id="Promise-prototype-catch"></a>

`Promise.prototype.catch`方法是`.then(null, rejection)`或`.then(undefined, rejection)`的别名，用于指定发生错误时的回调函数。

```javascript
getJSON('/posts.json').then(function(posts) {
  // ...
}).catch(function(error) {
  // 处理 getJSON 和 前一个回调函数运行时发生的错误
  console.log('发生错误！', error);
});
```

上面代码中，`getJSON`方法返回一个 Promise 对象，如果该对象状态变为`resolved`，则会调用`then`方法指定的回调函数；如果异步操作抛出错误，状态就会变为`rejected`，就会调用`catch`方法指定的回调函数，处理这个错误。另外，`then`方法指定的回调函数，如果运行中抛出错误，也会被`catch`方法捕获。

```javascript
p.then((val) => console.log('fulfilled:', val))
  .catch((err) => console.log('rejected', err));

// 等同于
p.then((val) => console.log('fulfilled:', val))
  .then(null, (err) => console.log("rejected:", err));
```

下面是一个例子。

```javascript
const promise = new Promise(function(resolve, reject) {
  throw new Error('test');
});
promise.catch(function(error) {
  console.log(error);
});
// Error: test
```

上面代码中，`promise`抛出一个错误，就被`catch`方法指定的回调函数捕获。注意，上面的写法与下面两种写法是等价的。

```javascript
// 写法一
const promise = new Promise(function(resolve, reject) {
  try {
    throw new Error('test');
  } catch(e) {
    reject(e);
  }
});
promise.catch(function(error) {
  console.log(error);
});

// 写法二
const promise = new Promise(function(resolve, reject) {
  reject(new Error('test'));
});
promise.catch(function(error) {
  console.log(error);
});
```

比较上面两种写法，可以发现`reject`方法的作用，等同于抛出错误。

### Promise.all\(promiseArray\)方法

* 将多个Promise对象实例包装，生成并返回一个新的Promise实例

```text
const p = Promise.all([p1, p2, p3]);
```

`p`的状态由`p1`、`p2`、`p3`决定，分成两种情况。

（1）只有`p1`、`p2`、`p3`的状态都变成`fulfilled`，`p`的状态才会变成`fulfilled`，此时`p1`、`p2`、`p3`的返回值组成一个数组，传递给`p`的回调函数。

（2）只要`p1`、`p2`、`p3`之中有一个被`rejected`，`p`的状态就变成`rejected`，此时第一个被`reject`的实例的返回值，会传递给`p`的回调函数。

* promise数组中所有的promise实例都变为resolve的时候，该方法才会返回
* 并将所有结果传递results数组中
* promise数组中任何一个promise为reject的话，则整个Promise.all调用会立即终止，并返回一个reject的新的promise对象

```javascript
var p1 = Promise.resolve(1),
    p2 = Promise.resolve(2),
    p3 = Promise.resolve(3);
Promise.all([p1, p2, p3]).then(function (results) {
    console.log(results);  // [1, 2, 3]
});
```

###  Promise.race\(\[p1, p2, p3\]\)

* Promse.race就是赛跑的意思
* 哪个结果获得的快，就返回那个结果
* 不管结果本身是成功状态还是失败状态

